Repository Skyblueballykid/kiva-crowd, pull requests merged in 2020-04, with the labels that each got.

#28 fix postgres container
  .env
  README.md
  docker-compose.yml
Labels: already done

#25 Frontend
  backend/local_app/kiva/statistics.py
  backend/local_app/kiva/tests/test_stats.py
  backend/local_app/kiva/urls.py
  backend/local_app/kiva/views.py
  frontend/public/index.html
  frontend/public/kiva-icon.png
  frontend/public/manifest.json
  frontend/src/api/StatsApi.js
  frontend/src/components/Navigation.js
  frontend/src/components/SearchView.js
  frontend/src/components/StatisticsView.js
  node_modules/.yarn-integrity
  yarn.lock
Labels: On Hold

#37 Update frontend
  .gitignore
  frontend/.eslintrc
  frontend/.huskyrc.json
  frontend/.lintstagedrc.json
  frontend/.prettierrc
  frontend/README.md
  frontend/config-overrides.js
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/api/LenderApi.js
  frontend/src/api/LoanApi.js
  frontend/src/api/StatsApi.js
  frontend/src/components/LenderTableView.js
  frontend/src/components/LoanTableView.js
  frontend/src/components/Navigation.js
  frontend/src/components/SearchView.js
  frontend/src/components/StatisticsView.js
  frontend/src/components/table/EditableCell.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/pages/LenderTableView.js
  frontend/src/pages/LoanTableView.js
  frontend/src/pages/LoanTableView.styles.js
  frontend/src/pages/StatisticsView.js
  frontend/src/serviceWorker.js
  frontend/yarn.lock
  node_modules/.yarn-integrity
  yarn.lock
Labels: WIP
